---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[open_resty]
    attributes:
      open_resty:
        nginx:
          lua_package_path: /var/www/?.lua;;
        lua_modules:
          - test_module
        testing: true
