name             "open_resty"
maintainer       "pseudomuto"
maintainer_email "david.muto@gmail.com"
license          "all_rights"
description      "Installs/Configures open_resty"
long_description "Installs/Configures open_resty"
version          "0.1.0"
